---
title: "cv"
format: html
---

# Chia-Chen Hsu

ORCID: 0009-0005-9034-461X  
Email: ckh5748@psu.edu  

---

## Education

Ph.D. in Economics, University of Washington, 2013
M.S. in Economics, University of Washington, 2010
B.S. in Economics and Political Science, University of Pittsburgh, 2006


- Ph.D in Energy, Environmental, and Food Economics, The Pennsylvania State University, 2024 -- Present

- M.S. in Agricultural Economics, National Taiwan University, 2021  

- B.S. in Economics, National Taipei University, 2017  

## Experience

### Research Assistant  
**Penn State University**  
2024 -- Present  

- Carbon Neutral Dairy Product Research  

### Research Assistant  
**National Taiwan University**  
2021 -- 2023  

- Participate in air quality and water management projects  
- Conduct spatial and statistical data integration, collection, and cleaning  

### Intern Group Leader  
**CSRone**  
2021 -- 2022  

- Check business ESG reports with GRI standards  
- Participate in the publication of Trends of Sustainability in Taiwan and APAC 2022

### Summer Intern  
**Taiwan Institute of Economic Research**  
Jul 2021 -- Aug 2021  

- Collect information on crowdfunding platforms  
- Publish fundraising trend report in FINDIT  

## Publications

- Hsu, C. C., Shr, Y. H. J. (2023). The impacts of water storage infrastructure on real property values and crop production. *Water Research*, 247, 120786.  

### Thesis

- *Pet Loss and Adolescent Mental Health*, Advisor: Yau-Huo Jimmy Shr  

## Conference Presentations

- The Impacts of Water Storage Infrastructure on Real Property Values and Crop Production.  
  The 12th Congress of Association of Environmental and Resource Economics, Tokyo, Japan, Aug 2023.  

- The Impacts of More Reliable Water Supply on Crop Production and Land Price: Evidence from a New Off-stream Reservoir in Taiwan.  
  EcoSummit 2023, Gold Coast, Australia, Jun 2023.  

- The Socio-Economic Benefits of Improving Water Availability: An Integrated Assessment Approach in the Zhuoshui River Basin in Taiwan.  
  AGU, Colorado, USA, Sep 2022.  

## Awards and Grants

- University Graduate Fellowship, Penn State University (2024--2025).  
- Excellent Teaching Assistant, National Taiwan University, Aug 2023.  
- Conference and Research Travel Grant, National Science and Technology Council (2022--2023).  

## Teaching Experience

**Teaching Assistant, National Taiwan University**

- Macroeconomic Theory (Graduate), Feb 2023 -- Jul 2023.  
- Applied Econometrics (Graduate), Sep 2022 -- Jan 2023.  
- Macroeconomics (Undergraduate), Feb 2022 -- Jul 2022.  
- Principle of Economics (Undergraduate), Sep 2021 -- Jan 2022.  
